### ISSUE TITLE
Align iOS BottomSheet defaults, or provide a way to override platform-specific  

### ISSUE THREAD

**Issue by millerf** [karseng9898/flutter_adaptive_widgets#2]
For example, this is `true` in `showCupertinoModalPopup`, and cannot be overriden in your library :

https://github.com/karseng9898/flutter_adaptive_widgets/blob/f6db16ee3fa61766424108a1a86106ddf4bc6874/lib/bottom_action_sheet/ios_bottom_action_sheet.dart#L13

**Comment by karseng9898** [comment]
Hi I have already updated the code, it is now fixed in v0.0.18. Thanks!!
